### ISSUE TITLE
Update search code sample for clarity 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#124]
# Search samples clarity
Currently the search code sample in the documentation is defined the following way: 

```py
index.search('botman')
```

We never explained to user that they need to define an index the following way: 
```py
index = client.index('movies')
```

Making the first example hard to understand. More than that, even if we did show the user how to create and use only the index instance, we also ask him to remember it from the previous code samples. 

To avoid **any** confusion, we should update the samples to the following: 

```py
client.index('movies').search('botman')
```

## Implementation

code samples should be updated where `index.` is used instead of `client.index`. 

For example:
Update `add_movies_json_1` `documents_guide_add_movie_1`  
```js
add_movies_json_1: |-
  const movies = require('./movies.json')
// previously index.addDocuments()...
  client.index('movies').addDocuments(movies).then((res) => console.log(res))
documents_guide_add_movie_1: |-
// previously index.addDocuments()...
  client.index('movies').addDocuments([{
    'movie_id': '123sq178',
    'title': 'Amelie Poulain'
  }])
```

and `getting_started_search_md`

```js
getting_started_search_md: |-
  \`\`\`js
// previously index.search()...
  client.index('movies').search('botman').then((res) => console.log(res))
  \`\`\`
```

## TODO

- [x] meilisearch-go https://github.com/meilisearch/meilisearch-go/pull/180
- [x] meilisearch-js https://github.com/meilisearch/meilisearch-js/pull/903
- [x] meilisearch-php
- [x] meilisearch-python https://github.com/meilisearch/meilisearch-python/pull/285
- [x] meilisearch-ruby https://github.com/meilisearch/meilisearch-ruby/pull/202

**Comment by bidoubiwa** [comment]
@alallema could this be done with the release v0.21 update?

**Comment by alallema** [comment]
The PHP SDK does not need any modification.

**Comment by bidoubiwa** [comment]
Done! 🚀
