### ISSUE TITLE
Code samples update

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#185]
Regarding the changes of the docs team in the past months, here are the changes we should apply in the SDKs 🤘
⚠️ Deadline: 07/04/2022

## New code samples regarding the new getting started

Follow the changes and the new code samples in this PR:
- https://github.com/meilisearch/documentation/pull/1280/files
- https://github.com/meilisearch/documentation/pull/1467/files 

⚠️ The second PR updates the first one!

## Replace `description` into `overview` and `genre` into `genres`

Update code samples according to the PR changes https://github.com/meilisearch/documentation/pull/1397/files

## Update geosearch guide

Update code samples according to the PR changes: https://github.com/meilisearch/documentation/pull/1498/files
## Remove unused code samples

Following https://github.com/meilisearch/documentation/pull/1230/files

## Update the primary key examples

Following https://github.com/meilisearch/documentation/pull/1242/files

## Add `settings_guide_sortable_1` code samples

This code sample is probably already presented in your code samples, please check it's present in every SDK

https://github.com/meilisearch/documentation/pull/1291/files

## Add `landing_getting_started_1` code samples

- backend languages: client initialization + documents addition.
- frontend languages: client initialization + search.
- frameworks: client initialization + documents addition.

The data these samples should contain are:
- Client creation with this host and key:
  - `"http://127.0.0.1:7700"` and `"masterKey"`
- **When** there is a search, search for:  **"philodelphia"**
- **When** there is document addion, use these data:
  - Index name: `movies` (without settings).
  - Data:
```jsonc
    { id: 1, title: 'Carol' },
    { id: 2, title: 'Wonder Woman' },
    { id: 3, title: 'Life of Pi' },
    { id: 4, title: 'Mad Max: Fury Road' },
    { id: 5, title: 'Moana' },
    { id: 6, title: 'Philadelphia' },
```

These instructions could vary for some integrations, like React, Rails, and Symfony.

# TODO

- [x] @brunoocasali adds new sample required for landing page
- [x] @brunoocasali creates an issue (with [the script](https://github.com/meilisearch/integration-automations/tree/main/issue-creator)) in every SDK to update the code samples, referring this central issue
- [x] The @meilisearch/integration-team updates the code samples in every SDK
- [x] @brunoocasali changes the label in the docs-team PRs from `code-sample-changes-needed` into `code-sample-changes-needed`. If @brunoocasali does not have the right, please inform Tommy to give the `triage` access for the docs-team repo.

FYI @dichotommy

**Comment by brunoocasali** [comment]
@dichotommy I created the label `code sample changes done` in the documentation repo, but I don't know if you will want to keep something like this, let me know what you think!

**Comment by brunoocasali** [comment]
Thanks, @bidoubiwa, @alallema for your hard work here (as always!) 🎉 🌮 🍣
