### ISSUE TITLE
Use index-swapping in relevant plugins instead of deleting index (v0.30.0)

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#223]
As per v0.30.0, [`index-swapping`](https://github.com/meilisearch/specifications/pull/192) is introduced. This feature gives the possibility to create a new `index`, and then swap it's name with another already existing `index`.

Currently, in some libraries, when we have to index content, we start by deleting the index (if it already existed), then recreate it. This results in a downtime for the user as the `index` is not accessible while the new one is being created.

This deleting/re-create method is used in in the following libraries:
- Gatsby
- Strapi
- docs-scraper
- rails
- Symfony 

We should update this method with the `swapping` method.

The common implementation looks like this:
- A new index is created with a generated name, for example an uuid4 to ensure the index name is not already used.
- Settings are added to this new index
- Documents are added to this new index
- Swap the new index with the old index.
- Delete the index with the generated name

# TODO

Issue:
- [ ] Create issue in the above-mentioned libraries

Implement this change in:

- [ ] ~Gatsby~
- [ ] ~docs-scraper~
- [ ] Strapi https://github.com/meilisearch/strapi-plugin-meilisearch/issues/786 
- [ ] Ruby on Rails https://github.com/meilisearch/meilisearch-rails/issues/267
- [ ] Symfony https://github.com/meilisearch/meilisearch-symfony/issues/277

**Comment by bidoubiwa** [comment]
Am I forgetting a repo?

**Comment by brunoocasali** [comment]
I think Rails can benefit from this feature, and maybe Symfony (but I'm not sure about it).

**Comment by curquiza** [comment]
Can we create issues in corresponding repo and close this one?

**Comment by brunoocasali** [comment]
I'm closing this, since all the issues were created in the repositories!
