### ISSUE TITLE
Add a test on yaml files linting in our CI's

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#231]
Sometimes we make changes on a yaml file and we do not format them correctly. Example a [duplicated key](https://github.com/meilisearch/meilisearch-go/pull/402). We also do not have a standard way for the syntax of our yamlfiles. 

In different repo's I already added the [yaml lint CI test](https://github.com/meilisearch/instant-meilisearch/blob/4a7300f167320037da562a1278ae0bfe2251c644/.github/workflows/tests.yml#L117-L120). For example, in `instant-meilisearch`.

The idea I'm suggesting is that we add this test in every repo that contains `yaml` files.

### TODO

This is what is required to make it work:
- Add the linter test in test.yaml, [example](https://github.com/meilisearch/instant-meilisearch/blob/4a7300f167320037da562a1278ae0bfe2251c644/.github/workflows/tests.yml#L117-L120)
- Create a `.yamllint` file containing the yaml rules. [Example](https://github.com/meilisearch/instant-meilisearch/blob/main/.yamllint.yml).

### Usage

To try out if your yaml files are correctly formated locally, you need to install the [`yamllint` tool](https://github.com/adrienverge/yamllint). 
Afterwards, run the following command:

```bash
yamllint .
```

## Repos

- [ ] [.Net SDK](https://github.com/meilisearch/meilisearch-dotnet) | [alallema](https://github.com/alallema/)
- [ ] [Dart SDK](https://github.com/meilisearch/meilisearch-dart) | [brunoocasali](https://github.com/brunoocasali/)
- [ ] [Golang SDK](https://github.com/meilisearch/meilisearch-go) | [alallema](https://github.com/alallema/)
- [ ] [Java SDK](https://github.com/meilisearch/meilisearch-java) | [alallema](https://github.com/alallema/)
- [ ] [JavaScript SDK](https://github.com/meilisearch/meilisearch-js) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [PHP SDK](https://github.com/meilisearch/meilisearch-php) | [brunoocasali](https://github.com/brunoocasali/)
- [ ] [Python SDK](https://github.com/meilisearch/meilisearch-python) | [alallema](https://github.com/alallema/)
- [ ] [Ruby SDK](https://github.com/meilisearch/meilisearch-ruby) | [brunoocasali](https://github.com/brunoocasali/)
- [ ] [Rust SDK](https://github.com/meilisearch/meilisearch-rust) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [Swift SDK](https://github.com/meilisearch/meilisearch-swift) | [brunoocasali](https://github.com/brunoocasali/)
- [ ] [Rails integration](https://github.com/meilisearch/meilisearch-rails)| [brunoocasali](https://github.com/brunoocasali/)
- [ ] [Symfony integration](https://github.com/meilisearch/meilisearch-symfony)| [brunoocasali](https://github.com/brunoocasali/)
- [ ] [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [Firestore extension](https://github.com/meilisearch/firestore-meilisearch) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [Gatsby plugin](https://github.com/meilisearch/gatsby-plugin-meilisearch) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [Strapi plugin](https://github.com/meilisearch/strapi-plugin-meilisearch) | [bidoubiwa](https://github.com/bidoubiwa/) 
- [ ] [VuePress plugin](https://github.com/meilisearch/vuepress-plugin-meilisearch) | [bidoubiwa](https://github.com/bidoubiwa/)
- [ ] [meilisearch-digitalocean](https://github.com/meilisearch/meilisearch-digitalocean) | [alallema](https://github.com/alallema/)
- [ ] [meilisearch-aws](https://github.com/meilisearch/meilisearch-aws) | [alallema](https://github.com/alallema/) 
- [ ] [meilisearch-gcp](https://github.com/meilisearch/meilisearch-gcp) | [alallema](https://github.com/alallema/)
- [ ] [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes) | [alallema](https://github.com/alallema/) 
- [ ] [docs-scraper](https://github.com/meilisearch/docs-scraper)| [alallema](https://github.com/alallema/)
- [ ] [meilisearch-migration](https://github.com/meilisearch/meilisearch-migration)| [alallema](https://github.com/alallema/)

**Comment by brunoocasali** [comment]
I think this is a very good addition. Should we add only to repositories with code-samples?

**Comment by bidoubiwa** [comment]
Maybe the once that have a `publishing` CI so that we avoid discovering the fail after release. What do you think?

**Comment by brunoocasali** [comment]
But I think all the repositories with a `publishing` action have code-samples, no?

**Comment by brunoocasali** [comment]
Hm, yeah, thinking about it now, I think every repo that has GitHub Actions :)

**Comment by bidoubiwa** [comment]
Waiting on @alallema approval before creating the issues on the related repo's

**Comment by alallema** [comment]
I really like the idea too! 🚀
