### ISSUE TITLE
Change `host` to `url` in the credentials naming

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#236]
## Context

When you create a client in multiple repositories, you must provide the URL to your Meilisearch instance. This `URL` parameter is often named `host`.

It may that sometimes the `host` variable is an internal name that refers to the URL, other times, the user needs to specify it. 

For example in Golang where the user needs to specify it: 

```go
  client := meilisearch.NewClient(meilisearch.ClientConfig{
    Host: "http://localhost:7700",
  })
```

Or internally in [PHP for example](https://github.com/meilisearch/meilisearch-php/search?q=host).

## Changes

We do not think `host` is the most appropriate name, and `url` is way more clear in what it expects. Thus, we  decided to change the parameter name `host` to `url`. This should be changed both on the user side, and internally.

Some repos do not have any mention of `host`, very few of them (only in tests names for example). 

## TODO

Changes must be applied in all repos.

- [x] [.Net SDK](https://github.com/meilisearch/meilisearch-dotnet)
- [x] [Dart SDK](https://github.com/meilisearch/meilisearch-dart)
- [ ] [Golang SDK](https://github.com/meilisearch/meilisearch-go)
- [x] [Java SDK](https://github.com/meilisearch/meilisearch-java)
- [ ] [JavaScript SDK](https://github.com/meilisearch/meilisearch-js)
- [x] [PHP SDK](https://github.com/meilisearch/meilisearch-php)
- [x] [Python SDK](https://github.com/meilisearch/meilisearch-python)
- [x] [Ruby SDK](https://github.com/meilisearch/meilisearch-ruby)
- [ ] [Rust SDK](https://github.com/meilisearch/meilisearch-rust)
- [ ] [Swift SDK](https://github.com/meilisearch/meilisearch-swift)
- [ ] [Laravel-Scout integration](https://github.com/laravel/scout)
- [x] [Rails integration](https://github.com/meilisearch/meilisearch-rails)
- [x] [Symfony integration](https://github.com/meilisearch/meilisearch-symfony)
- [ ] [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch)
- [ ] [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js)
- [ ] [Firestore extension](https://github.com/meilisearch/firestore-meilisearch)
- [ ] [Gatsby plugin](https://github.com/meilisearch/gatsby-plugin-meilisearch)
- [ ] [Strapi plugin](https://github.com/meilisearch/strapi-plugin-meilisearch)

**Comment by brunoocasali** [comment]
Most of the SDKs have this change, and I don't think we should keep this open anymore :) 

I'll close this in favor or more keeping more relevant discussions.
