### ISSUE TITLE
Changes related to Meilisearch v1.7.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#296]
This issue gathers the changes related to the v1.7.0 of Meilisearch that will impact the integrations scope.

📅 Release date: 2024-03-11

### Pre-release

- [x] With the help of the Product team and [this CI](https://github.com/meilisearch/meilisearch/actions/workflows/sdks-tests.yml), define which integrations should be updated and how (New feature? Update README? Update tests?)
Fill in the "What to implement?" section below in this issue.
- [x] Create a branch by running [Octopus script](https://github.com/meilisearch/integration-automations/tree/main/octopus): only open branches for the integrations we choose to update (defined in the previous step) + Kubernetes repository + Cloud provider repository (changing the version)
- [x] Update integrations according to the decisions (cf "What to implement?" section below in this issue 👇)
  - [x] JS: https://github.com/meilisearch/meilisearch-js/issues/1632
  - [x] PHP: stabilize `scoreDetails`
  - [x] Rust: stabilize `scoreDetails`
  - [x] Ruby: stabilize `scoreDetails`
  - [x] Dart: stabilize `scoreDetails`
  - [x] Python: Hybrid search
  - [x] Instant Meilisearch: use new meilisearch-js version
- [x] Add code samples for the chosen up-to-date integrations with the new version of Meilisearch. https://github.com/meilisearch/documentation/issues/2741
- [x] Update the library version of the related integrations and prepare the changelogs
  - [x] JS
  - [x] PHP
  - [x] Rust
  - [x] <s>Ruby -> NOT needed</s>
  - [x] Dart
  - [x] Python
  - [x] Instant Meilisearch

### Release day

- [x] Release the integrations
  - [x] JS
  - [x] PHP
  - [x] Rust
  - [x] Python
  - [x] Instant Meilisearch
- [x] Merge the related PR in [K8s repository](https://github.com/meilisearch/meilisearch-kubernetes/pulls)
- [x] Publish [DevOps tools](https://github.com/meilisearch/cloud-providers/):
  - [x] create the git tag
  - [x] publish images (steps are in CONTRIBUTING.md)
- [x] Open issues in the repositories that are not up-to-date with the latest version of Meilisearch (**including code samples**)
  - [x] For `scoreDetails` stabilization
  - [x] For the new usage of OpenAI embedders
- [x] Ensure the issues related to `scoreDetails` feature are up to date with this stabilization in different repositories (close them or update them)

### Stabilize `scoreDetails` experimental feature

Issue: https://github.com/meilisearch/meilisearch/issues/4359

`showRankingScoreDetails` parameter was previously present as experimental since [v1.3.0](https://github.com/meilisearch/meilisearch/releases/v1.3.0). The boolean `scoreDetails` had to be activated as `true` in the `/experimental-features` route to make `showRankingScoreDetails` available.

It means this feature is already available in some integrations.
<details>
<summary>Here is the details</summary>

Not present in
- Dotnet
- Java
- Go (but showRankingScore is)
- Rust (but showRankingScore is, and some tests to activate scoreDetails are present)
- Swift (but showRankingScore is)

Already present in:
- Dart
- JS
- PHP
- Python
- Ruby
</details>

**TODO**
- [x] JS: Update tests related to `scoreDetails`
- [x] PHP: Update tests related to `scoreDetails`
- [x] Rust: Update tests and [code-samples](https://github.com/meilisearch/meilisearch-rust/blob/d563253f4ea7bb252b85c87ce28581c00f0efc7a/.code-samples.meilisearch.yaml#L1598) related to `scoreDetails` + `scoreDetails` in the code base -> but `showRankingScoreDetails` is NOT present in the library
- [x] Dart: remove `scoreDetails` mention in code base + update the commented test
- [x] Ruby: remove mention of `scoreDetails` in README + update tests

The following integrations will not have the feature available for the release day: Dotnet, Java, Go, Rust and Swift

### Improvement with OpenAI model for Hybrid search

Issue: https://github.com/meilisearch/meilisearch/issues/4394

<details>
<summary>Hybrid search & embedders are already available in some integrations 👇</summary>

- JS
- PHP
- Python

But not in
- Dotnet
- Dart
- Go
- Java
- Ruby
- Rust
- Swift
</details>

`dimensions` field is now available in the `openAi` embedder settings

Example:

```json
"embedders": {
  "large": {
    "source": "openAi",
    "model": "text-embedding-3-large",
    "dimensions": 512
  }
}
```

**TODO**
- [x] JS: make `dimensions` field work for OpenAi models
- [X] PHP -> already working
- [x] Python: make `dimensions` field work for OpenAi models

The following integrations will not have the Hybrid search feature, so the OpenAI improvements, available for the release day: Dart, Dotnet, Java, Go, Ruby, Rust and Swift

### New `/logs` experimental route

Related issue: https://github.com/meilisearch/meilisearch/issues/4317

We will not implement anything in our SDKs because this new route is mostly an internal & debugging tool than a real usage in code base

**Comment by curquiza** [comment]
Closing this issue since all the issues of missing features have been opened, and old issues updated in the different repositories

well done everyone 🎉
