### ISSUE TITLE
Changes related to Meilisearch v1.11.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#303]
This issue gathers the changes related to the v1.11.0 of Meilisearch that will impact the integrations scope.

📅 Release date: 28 October 2024

### Pre-release

- [x] With the help of the [changelog](https://github.com/meilisearch/engine-team/pulls) &  [this CI](https://github.com/meilisearch/meilisearch/actions/workflows/sdks-tests.yml), define which integrations should be updated and how (New feature? Update README? Update tests?)
  - [x] **Fill in** the "What to implement?" section below in this issue 👇. Minial implementation: PHP, JS, Instant-meilisearch.
  - [x] Open implementation issues in repositories that need implementation.
  - [x] Discuss with the Product team if needed. At least share this issue to let them know about the decisions.
- [x] Create a branch by running [Octopus script](https://github.com/meilisearch/integration-automations/tree/main/octopus): only open branches for the integrations we choose to update (defined in the previous step) + Kubernetes repository + Cloud provider repository (changing the version)
- [x] Update integrations according to the decisions (cf "What to implement?" section below in this issue 👇)
⚠️ If possible, this step is done before pre-release, once the feature is ready thanks to the prototype released by the engine team
  - [x] JS: implementation + fix tests
  - [x] PHP: implementation + fix tests
  - [x] Go: Fix AI tests (maybe implementation is required)
  - [x] Python: fix AI tests (maybe implementation is required)
  - [X] Ruby: fix AI tests
- [x] Add code samples for the chosen up-to-date integrations with the new version of Meilisearch
- [x] Update the library version of the related integrations and prepare the changelogs

### Release day

- [x] Release the integrations
  - [x] Release JS
  - [x] Release PHP
  - [x] Go
  - [x] Python
  - [x] Ruby
  - [x] Release Instant-meilisearch with new version of meilisearch-js
- [x] Merge the related PR in [K8s repository](https://github.com/meilisearch/meilisearch-kubernetes/pulls)
- [x] Publish [DevOps tools](https://github.com/meilisearch/cloud-providers/):
  - [x] create the git tag
  - [x] publish images (steps are in CONTRIBUTING.md)
- [x] Remove useless AWS images (by using our [internal script](https://github.com/meilisearch/integration-automations/tree/main/cloud-providers))
- [x] Update AI-search related issues with changes in v1.11
- [x] Open issues in the repositories that are not up-to-date with the latest version of Meilisearch (**including code samples**)
- [x] Update already existing issues in repositories about AI search

### Experimental - AI search changes

Related issue in the engine:
- https://github.com/meilisearch/meilisearch/issues/4733
- https://github.com/meilisearch/meilisearch/issues/4873

Breaking:
* When using the semantic or the hybrid search, `hybrid.embedder` is now a **mandatory** parameter in `GET and POST /indexes/{:indexUid}/search`
* As a consequence, it is now **mandatory** to pass `hybrid` even for full-vector search (with only `vector` and not `q`)
* `embedder` is now a **mandatory** parameter in `GET and POST /indexes/{:indexUid}/similar`
* Ignore non-zero `semanticRatio` when `vector` is passed but not `q`: a semantic search will be performed.

Changes:
* A new sub setting in `embedders` setting to enable binary quantization and speed up indexing speed.
* The default model for OpenAI is now `text-embedding-3-small` instead of `text-embedding-ada-002`.
* Limit the maximum length of a rendered document template: when the source of an embedder is set to `huggingFace`, `openAi`, `rest` or `ollama`, then `documentTemplateMaxBytes` is now available as an optional parameter. This parameter describes the number of bytes in which the rendered document template text should fit when trying to embed a document. Longer texts are truncated to fit.
* Add the ability to query whether a field is searchable in `documentTemplate`: use `field.is_searchable`:  `true` if the field is a searchable attribute, otherwise `false`.

TODO:
- [x] JS: implementation + fix tests - https://github.com/meilisearch/meilisearch-js/issues/1714
- [x] PHP: implementation + fix tests - https://github.com/meilisearch/meilisearch-php/issues/682
- [x] Go: fix tests - https://github.com/meilisearch/meilisearch-go/issues/578
- [x] Python: fix tests - https://github.com/meilisearch/meilisearch-python/issues/1019
- [x] Ruby: fix tests - no issue, done in https://github.com/meilisearch/meilisearch-ruby/pull/571

### Support facet distribution for federated search

Related issue in the engine: https://github.com/meilisearch/meilisearch/issues/4932

* Request facet distributions and facet stats in your federated search, by using `federation.facetsByIndex` in the POST `POST /multi-search` route.
* Merge the returned facets in a single facet distribution and stats that is global to the entire request, by using `federation.mergeFacets` in the POST `POST /multi-search` route.

TODO:
- [x] JS: https://github.com/meilisearch/meilisearch-js/issues/1713
- [x] PHP: https://github.com/meilisearch/meilisearch-php/issues/681

### Experimental - STARTS_WITH operator

Related issue in the engine: https://github.com/meilisearch/meilisearch/issues/4872

Filter with the newly introduced `STARTS_WITH` operator

TODO:
- [X] JS: nothing to implement 🎉
- [X] PHP: nothing to implement 🎉

### Language setting enhancement: support ISO-639-1 languages code

Related issue in the engine: https://github.com/meilisearch/meilisearch/issues/4827

* Add iso-639-1 variants
* Convert iso-639-1 into iso-639-3

TODO:
- [X] JS: nothing to implement 🎉
- [X] PHP: nothing to implement 🎉
