### ISSUE TITLE
Update SearchableAttributes code-sample example

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#75]
# Changes in code-sample 
## Introduction 

In the complete rewrite of the [searchable and displayed attributes guide](https://docs.meilisearch.com/references/searchable_attributes.html#searchable-attributes) a decision to change the code-sample of the searchable Attribute has been taken.

### Previously 

Previously there were too many attributes added to the list. Which made the example lose in clarity.
```yaml
field_properties_guide_searchable_1: |-
  $ curl \
    -X POST 'http://localhost:7700/indexes/movies/settings' \
    --data '{
        "searchableAttributes": [
            "uid",
            "movie_id",
            "title",
            "description",
            "poster",
            "release_date",
            "rank"
        ]
    }'
```
### New 

The following update of this code-sample limits the number of attributes used and is also more compliant with the official movie.json dataset used in many parts of the documentation.

```yaml
field_properties_guide_searchable_1: |-
  $ curl \
    -X POST 'http://localhost:7700/indexes/movies/settings' \
    --data '{
        "searchableAttributes": [
            "title",
            "description",
            "genre"
        ]
    }'

```

### TODO

All SDK's present in the documentation should update their `.code-samples.meilisearch.yaml` accordingly.

- [ ] [documentation](https://github.com/meilisearch/documentation)
- [x] [meilisearch-js](https://github.com/meilisearch/meilisearch-js)
- [x] [meilisearch-python](https://github.com/meilisearch/meilisearch-python)
- [x] [meilisearch-php](https://github.com/meilisearch/meilisearch-php)
- [x] [meilisearch-ruby](https://github.com/meilisearch/meilisearch-ruby)
- [x] [meilisearch-go](https://github.com/meilisearch/meilisearch-go)
- [x] [meilisearch-rust](https://github.com/meilisearch/meilisearch-rust)

related: https://github.com/meilisearch/documentation/pull/679

**Comment by curquiza** [comment]
Closing this issue since all the integration tools are up to date 😁
