### ISSUE TITLE
Move dependabot config in github repo

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#95]
>Dependabot is moving natively into GitHub, and we need a quick update from you to finish the move! Click "Create pull request" to open a pull request on instant-meilisearch with a new config file. When you merge the pull request, we'll swap outdependabot-preview for a new dependabot app, and you'll be all set.
> The pull request moves the UI configuration to a config file in.github/dependabot.yml. The config file uses the new syntax...

I'm not sure if this means it would be a best practice to do so, but in the case of meilisearch/instant-meilisearch#255 we still have every week the update dump for `jest-environment-jsdom`

I can say to dependabot : `@dependabot ignore this major version` but when we'll go to the next major he will suggest it.

I did not find how to remove it in the dashboard of dependabot but I could find how to do it in a config file:
```yaml
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - skip-changelog
  versioning-strategy: increase
  ignored_updates:
      - match:
          dependency_name: "jest-environment-jsdom"
          # The version_requirement specifies the versions to ignore.
          # The range format is specific to the package manager
          # (e.g., ^1.0.0 for JS, or ~> 2.0 for Ruby).
          version_requirement: "25.5"
  rebase-strategy: disabled
```

This is the generated config file that I picked up from the dashboard, and I added `jest-environment-jsdom` in the ignored_updates.

So my question is: 

Should we go for a config file in every integration package?

## Dependabot file in every integration ❤️

Example: https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/.github/dependabot.yml

### Cons
In case of updates, a lot of repos needs to be changed. Maybe not that hard to do thanks to https://github.com/meilisearch/integration-scripts/tree/main/generic-files-updater

### Pros

Dependabot context stays in the repository

### Cons

Far away from the repository. UI limits options.

### Pros

Nothing to change.

## TODO

Not guarantee that all integrations have a package manager. Please hit checkbox if not needed.

###  SDKs for MeiliSearch API

- [x] [Golang](https://github.com/meilisearch/meilisearch-go)
- [x] [Java](https://github.com/meilisearch/meilisearch-java)
- [x] [JavaScript](https://github.com/meilisearch/meilisearch-js)
- [x] [PHP](https://github.com/meilisearch/meilisearch-php)
- [x] [Python](https://github.com/meilisearch/meilisearch-python)
- [x] [Ruby](https://github.com/meilisearch/meilisearch-ruby)
- [x] [Rust](https://github.com/meilisearch/meilisearch-rust)
- [Swift](https://github.com/meilisearch/meilisearch-swift) (not supported by dependabot)

### 🏗 Framework Integrations

- [x] [Laravel Scout](https://github.com/meilisearch/meilisearch-laravel-scout)
- [x] [Symfony](https://github.com/meilisearch/meilisearch-symfony)

###  Front-End Integrations

- [ ] [Angular](https://github.com/meilisearch/meilisearch-angular)
- [ ] [React](https://github.com/meilisearch/meilisearch-react)
- [x] [Vue](https://github.com/meilisearch/meilisearch-vue)
- [ ] [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch): a plugin to establish the communication between MeiliSearch and the open-source [InstantSearch](https://github.com/algolia/instantsearch.js) tools (powered by Algolia) for your front-end application.
- [ ] [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js): a search bar integration for all kinds of documentation.

### 🐳 DevOps Tools

- [x] [meilisearch-digitalocean](https://github.com/meilisearch/meilisearch-digitalocean): how to deploy a MeiliSearch instance on DigitalOcean. See this [dedicated page](https://docs.meilisearch.com/create/how_to/digitalocean_droplet.html) to use it.
- [ ] [meilisearch-aws](https://github.com/meilisearch/meilisearch-aws): how to deploy a MeiliSearch instance on AWS. See this [dedicated page](https://docs.meilisearch.com/create/how_to/aws.html) to use it.
- [ ] [meilisearch-gcp](https://github.com/meilisearch/meilisearch-gcp): how to deploy a MeiliSearch instance on GCP.
- [ ] [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes): how to deploy a MeiliSearch instance on Kubernetes.
- [ ] [Cloud Scripts](https://github.com/meilisearch/cloud-scripts): centralize all the configurations to help our DevOps tool handle MeiliSearch.

###  Misc

- [x] [docs-scraper](https://github.com/meilisearch/docs-scraper): a scraper tool to automatically read the content of your documentation and store it into MeiliSearch.

### 🧩 Platform Plugins

- [x] [VuePress](https://github.com/meilisearch/vuepress-plugin-meilisearch)
- [x] [Strapi](https://github.com/meilisearch/strapi-plugin-meilisearch)

### 🧑‍🔧 Work In Progress

- [x] [.Net](https://github.com/meilisearch/meilisearch-dotnet)
- [Dart](https://github.com/meilisearch/meilisearch-dart)  (not supported by dependabot)
- [ ] [meilisearch-wordpress](https://github.com/meilisearch/meilisearch-wordpress)
- [ ] [Rails](https://github.com/meilisearch/meilisearch-rails)

**Comment by curquiza** [comment]
I think this is a good idea to generalize it because :
- we can do more customization with the config file (if I understand what you say)
- we keep centralizing all the repo information/settings in the GitHub repo itself, which is really more convenient than switching to another dashboard.

**Comment by bidoubiwa** [comment]
@curquiza  @alallema

**Comment by curquiza** [comment]
Done everywhere 😌
